### PR TITLE
Build glibd library from autogenerated bindings

### PR DESCRIPTION
**Pull request by ximion**
Hi!

This enhances the Meson build definition to not only generate the `girtod` binary, but also produce a new `glibd-2.0` binary.
I am using `girtod` in a few projects now, which are all non-GUI and therefore only need GLib (and an additional library wrapped). Always building the entire GLib D bindings source code is incredibly time consuming for projects, and given that pretty much every single project using gir-to-d will need to link against the wrapped glib D code, I think it makes a lot of sense to ship an autogenerated glibd library with the gir-to-d binary itself.

The new code messes with Meson quite a bit. Meson (and make/ninja) have the concept of "generators" to generate new file targets using a custom command. The problem is that we need to know the names of the generated files in advance, which is not (easily) the case with `girtod` which generates a bunch of new directories and D sources.
We could split out the generate/build step into an entirely new custom command, but then we would have to do all the D compiler detection, build-flags setting etc. manually again, which sucks and will break for sure at some point.

The solution I went with here due to that is to build a scratch girtod binary when configuring the Meson project, and use that to produce the sources to then use a regular library target with.
This has a drawback too, first it's quite ugly, and second when running ninja again, we will only ever recompile the girtod source code, but not regenerate the library sources with the new girtod. So, when developing girtod, this must be accounted for.

The wrap files for the new glibd library are taken from current GtkD Git master.

I know this is quite an invasive change, and I initially wanted to file a bug asking @MikeWey to give us some glibd library, but then I thought that providing a patch might be a better way to open this discussion.

Please give this patch a try!
Unfortunately I have absolutely no idea on how to implement this with dub - the only thing I can think of that might work with dub is to have two separate dub.json files, one building girtod, and the other one calling the generated girtod to produce library sources.

I hope you find this patch helpful! It will fix the code-duplication and recompilation issue for projects using Makefiles and Meson, for dub we will likely need a different solution though (unless dub fixes its global package registry support, in which case we could make it so that dub users could use the Meson-installed stuff as well). Easiest for dub would likely be to just ship pregenerated files in Git, which is a bit ugly as well though.

### CODE REVIEW

**Comment by MikeWey** [comment]
Even tough girtod and glibD are tied closely together, I think GlibD should be i a separate repository/package.

This would also allow you to do something like this for meson:

```meson
#
# Build interfaces from GIR
#
gir_to_d_prog = find_program('girtod')
gir_wrap_dir = source_root + '/src/'
gir_d_intf_dir = build_root + '/generated/'

message('Generating D interfaces from GIR...')
girtod_gen = run_command(gir_to_d_prog,
                         '-i', gir_wrap_dir,
                         '-o', gir_d_intf_dir,
                         '--print-files', 'relative,'+source_root)
if girtod_gen.returncode() != 0
    error('Unable to build D intefaces from GIR:\n' + girtod_gen.stderr())
endif
gir_bind_dir = include_directories('generated')

# Enlist D GIR interface sources
gir_binding_sources = girtod_gen.stdout().strip().split('\n')
```

And use `dub fetch` + `dub run` in dubs pregenerate command to generate the source.

**Comment by ximion** [comment]
@MikeWey I don't object to that ^^
Would you want to create a new repository for that?

**Comment by MikeWey** [comment]
It still needs some work, but you can find it here:

https://github.com/gtkd-developers/GlibD

**Comment by ximion** [comment]
@MikeWey Excellent, thank you!
I'll prepare a PR for the Meson definition, because I found a few things that can be improved, and as soon as there is a first release I'll be using this library in my projects instead of always regenerating the data from scratch.

**Comment by ximion** [comment]
Looking at this PR again, it actually contains some improvements to the Meson definition that are useful on their own. I'll file a new PR for those.

**Pull request closed without merging**
